# Learning Parameters
LEARNING_RATE : 0.001
BATCH_SIZE : 128
TRAINING_ITERS : 100000
DISPLAY_STEP : 1

# Network Data Parameters
INPUT_SHAPE : [39, 600, 3] # Input Image shape
OUTPUT_SHAPE : [2] # Total classes as vector

# Datasets
TRAINING_DATA : "/Users/therold/Google Drive/Uni/DeepAudio/spectros/train.csv"
TEST_DATA : "/Users/therold/Google Drive/Uni/DeepAudio/spectros/test.csv"

# Logging
LOG_PATH : "logs"
SNAPSHOT_PATH : "snapshots"
